chore(rofi-tmux): use printfc and update new lib paths

diff --git a/.local/bin/rofi-tmux b/.local/bin/rofi-tmux
--- a/.local/bin/rofi-tmux
+++ b/.local/bin/rofi-tmux
@@ -2,27 +2,28 @@
 
 # "Open running tmux sessions or start new sessions using tmuxp"
 
-if ! command -v rofi &>/dev/null; then
-  echo "rofi could not be found. Please install it."
-  exit 1
-fi
-
 XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config/}
 ENV_FILE="$XDG_CONFIG_HOME/scriptenv"
 
-if [ -z "$ENV_FILE" ]; then
-  echo "scriptenv is missing at $XDG_CONFIG_HOME"
-  return 1
-fi
+. "$HOME/.local/lib/printfc.sh"
+. "$HOME/.local/lib/tmux_functions.sh"
 
-source "$ENV_FILE"
-
-if [ -z "$TERMCMD" ] || [ -z "$EDITOR" ]; then
-  echo "Error: TERMCMD or EDITOR env at scriptenv not found"
+if ! command -v rofi &>/dev/null; then
+  printfc FATAL "rofi could not be found. Please install it."
   exit 1
 fi
 
-source "$(dirname "$(realpath $0)")/lib/tmux_functions.sh"
+if [ -z "$ENV_FILE" ]; then
+  printfc FATAL "scriptenv is missing at $XDG_CONFIG_HOME"
+  return 1
+else
+  . "$ENV_FILE"
+fi
+
+if [ -z "$TERMCMD" ] || [ -z "$EDITOR" ]; then
+  printfc FATAL "TERMCMD or EDITOR env at scriptenv not found"
+  exit 1
+fi
 
 _rofi() {
   rofi -dmenu -i -no-levenshtein-sort -width 1000 -p "$mode" -mesg "${HELP}" -kb-custom-1 "${delete}" -kb-custom-2 "${switch_mode}" "$@"
